name: FizzBuzz

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  fizzbuzz:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: [3.8.1]
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: Run
        run: dart main.dart
